### ISSUE TITLE
New hosting for test environment

### ISSUE THREAD

**Issue by silivastruflorin** [sibies/Bt.IPay.Net#4]
It seems that IPay is migrating the hosting for test env. from https://ecclients.btrl.ro:5443 to https://ecclients-sandbox.bt rl.ro
![image](https://github.com/sibies/Bt.IPay.Net/assets/31577537/de7f804f-3ac8-4d90-9a9e-d900af6d3966)

**Comment by totpero** [comment]
https://btepos.ro/documentatie

**Comment by totpero** [comment]
Hi @silivastruflorin 
This is already implemented in v2.2.0 last release.
Thanks for your feedback 👍

**Comment by silivastruflorin** [comment]
> Hi @silivastruflorin This is already implemented in v2.2.0 last release. Thanks for your feedback 👍

Awesome! Great job and thanks!
